# Generated by Django 5.2.4 on 2025-08-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rool_no', models.IntegerField(unique=True)),
                ('student_class', models.CharField(max_length=50)),
                ('date_of_of_birth', models.DateField()),
                ('adress', models.TextField()),
            ],
        ),
    ]
