# Generated by Django 5.2.4 on 2025-08-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
